name: Python Flask Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m venv venv
        . venv/bin/activate
        pip install -r requirements.txt

    # Step 4: Zip the Flask app (for simplicity, zipping the whole project)
    - name: Create artifact
      run: zip -r flask_app.zip .

    # Step 5: Upload the artifact
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: flask-app-artifact
        path: flask_app.zip
